spring:
  application:
    name: ceylon-wild-capture

  profiles:
    active: dev

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}          # 1 hour in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION} # 7 days in milliseconds

