spring:
  application:
    name: ceylon-wild-capture

  profiles:
    active: dev

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000          # 1 hour
  refresh-expiration-ms: 604800000 # 7 days

